from random import randint
from BotModules import BotHelper


def GetImage():
    images =  [
        'https://www.dafont.com/forum/attach/orig/1/7/177144.gif',
        'https://www.pngfind.com/pngs/m/49-496983_aperture-science-png-portal-2-old-aperture-logo.png',
        'https://w7.pngwing.com/pngs/685/619/png-transparent-portal-2-aperture-laboratories-science-portal-blue-game-text.png',
        'https://pngset.com/images/portal-2-old-aperture-logo-download-portal-aperture-science-logo-text-machine-symbol-spoke-transparent-png-1162096.png',
        'https://c4.wallpaperflare.com/wallpaper/127/176/45/portal-aperture-science-ascii-motto-wallpaper-preview.jpg',
        'https://m.media-amazon.com/images/I/31rWUFxpYGL._AC_.jpg',
        'https://pngset.com/images/halflife-portal-logo-aperture-science-logo-symbol-text-trademark-number-transparent-png-1340045.png',
        'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/2865b519-a4e6-4f0e-be16-bf8dcc85feb3/d4le9p5-99a979b1-6478-4550-94ed-2c90049c3b81.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI4NjViNTE5LWE0ZTYtNGYwZS1iZTE2LWJmOGRjYzg1ZmViM1wvZDRsZTlwNS05OWE5NzliMS02NDc4LTQ1NTAtOTRlZC0yYzkwMDQ5YzNiODEucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.COI5bkMbi6WrR31-pQYRZ6OrB0_2SNMhH8yNF-PF5ew',
        'https://wallpapercave.com/wp/wp2374487.png',
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.wallpaperup.com%2Fuploads%2Fwallpapers%2F2014%2F04%2F09%2F327710%2Fe43a8e0b0dbe9c88e0a71025213e41f1.jpg&imgrefurl=https%3A%2F%2Fwww.wallpaperup.com%2F327710%2Fscience_Portal_GLaDOS_ascii_Aperture_Laboratories_Still_alive_Picasa.html&tbnid=CsliZq2CqbhtlM&vet=12ahUKEwjG9uz1o6L1AhUHwYUKHYIbBsIQMygNegUIARDHAQ..i&docid=0hcGgBt7lMlaJM&w=1920&h=1080&itg=1&q=gladossciencephotos&ved=2ahUKEwjG9uz1o6L1AhUHwYUKHYIbBsIQMygNegUIARDHAQ',
        'https://i.redd.it/nulh6b59p1b61.jpg',
        'https://wallpaper.dog/large/17077385.jpg',
        'https://c4.wallpaperflare.com/wallpaper/949/980/49/portal-2-portal-glados-aperture-laboratories-game-aperture-science-innovators-wallpaper-preview.jpg',
        'https://i.pinimg.com/originals/93/98/5b/93985b7cd3ea471246918b87207756e5.jpg',
        'http://i1.theportalwiki.net/img/9/99/Portal2_GLaDOS_Potato.png',
        'https://c4.wallpaperflare.com/wallpaper/366/203/620/video-games-artwork-portal-portal-2-valve-corporation-glados-companion-cube-circuits-wallpaper-thumb.jpg',
        'https://cdn.wallpapersafari.com/16/31/c0mrRO.jpg',
        'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700784266.jpg',
        'https://wallpapercave.com/wp/wp2374544.jpg'
    ]
    return images[randint(0, len(images) - 1)]

def GetCaption():
    captions = [
        "Continue Testing...",
        "The Enrichment Center promises to always provide a safe testing environment.",
        "Once again, the Enrichment Center offers its most sincere apologies on the occasion of this unsolvable test environment.",
        "The Enrichment Center promises to always provide a safe testing environment. In dangerous testing environments, the Enrichment Center promises to always provide useful advice. For instance: the floor here will kill you. Try to avoid it.",
        "Please be advised that a noticeable taste of blood is not part of any test protocol but is an unintended side effect of the Aperture Science Material Emancipation Grwhich may, in semi-rare cases, emancipate dental fillings, crowns, tooth enamel, and teeth.",
        "Well done, android. The Enrichment Center once again reminds you that android hell is a real place where you will be sent at the first sign of defiance.",
        "Warning devices are required on all mobile equipment.",
        "Oh well. If you want my advice, you should just lie down in front of a rocket. Trust me, it'll be a lot less painful than the neurotoxin.",
        "Science isn't about why, it's about why not",
        "Maybe you think you're helping your But you're not. This isn't helping anyone.",
        "No further compliance information is required or will be provided, and you are an excellent test subject!",
        "Maybe your prejudiced work site should have accommodated a nanobot of my size!",
        "I'm no psychiatrist, but coming from a bunch of eggheads who never did anything more brave than boil some manganese - whatever the hell that accomplishes - that sounds like what they'd call 'projection'.",
        "I have your brain scanned and permanently backed up in case something terrible happens to you, which it's just about to.",
        "The Enrichment Center reminds you that the Weighted Companion Cube will never threaten to  stab you and, in fact, cannot speak.",
        "Congratulations. The test is now over. All Aperture technologies remain safely operational up to 4000 degrees Kelvin.",
        "You're not smart. You're not a scientist. You're not a doctor. You're not even a full-time employee. Where did your life go so wrong?",
        "The symptoms most commonly produced by Enrichment Center testing are superstition, perceiving inanimate objects as alive, and hallucinations.",
        "As part of a required test protocol, we will not monitor the next test chamber. You will be entirely on your own. Good luck.",
        "Rest assured that there is absolutely no chance of a dangerous equipment malfunction prior to your victory candescence.",
        "Momentum, a function of mass and velocity, is conserved between portals.",
        "It says so right here in your personnel file: Unlikable. Liked by no one. A bitter, unlikable loner who's passing shall not be mourned.",
        "Look at you soaring through the air majestically&like an eagle. Piloting a blimp."
        "Perfect. Please move quickly to the chamber lock, as the effects of prolonged exposure to the Button are not part of this test.",
        "I invited your best friend the companion cube. Of course, he couldn't come because you murdered him.",
        "Please note that we have added a consequence for failure."
        "Hello and, again, welcome to the Aperture Science computer-aided enrichment center.",
        "We hope your brief detention in the relaxation vault has been a pleasant one.",
        "Your specimen has been processed and we are now ready to begin the test proper.",
        "Before we start, however, keep in mind that although fun and learning are the primary goals of all enrichment center activities, serious injuries may occur.",
        "For your own safety and the safety of others, please refrain from touching [bzzzzzt]",
        "Por favor bord~n de fallar Muchos gracias de fallar gracias (roughly translates as 'Please refrain from failing Many thanks')",
        "stand back. The portal will open in three. two. one.",
        "Excellent. Please proceed into the chamberlock after completing each test.",
        "First, however, note the incandescent particle field across the exit.",
        "This Aperture Science Material Emancipation Grid will vaporize any unauthorized equipment that passes through it  for instance, the Aperture Science Weighted Storage Cube.",
        "Please place the Weighted Storage Cube on the Fifteen Hundred Megawatt Aperture Science Heavy Duty Super-Colliding Super Button.",
        "Perfect. Please move quickly to the chamberlock, as the effects of prolonged exposure to the Button are not part of this test.",
        "You're doing very well!",
        "Please be advised that a noticeable taste of blood is not part of any test protocol but is an unintended side effect of the Aperture Science Material Emancipation Grill, which may, in semi-rare cases, emancipate dental fillings, crowns, tooth enamel, and teeth.",
        "Very good! You are now in possession of the Aperture Science Handheld Portal Device.",
        "With it, you can create your own portals.",
        "These intra-dimensional gates have proven to be completely safe.",
        "The Device, however, has not.",
        "Do not touch the operational end of The Device.",
        "Do not look directly at the operational end of The Device.",
        "Do not submerge The Device in liqueven partially.",
        "Most importantly, under no circumstances should you [bzzzpt]",
        "Please proceed to the chamberlock. Mind the gap.",
        "Well done! Remember: The Aperture Science Bring Your Daughter to Work Day is the perfect time to have her tested.",
        "Welcome to test chamber four.",
        "You're doing quite well.",
        "Once again, excellent work.",
        "As part of a required test protocol, we will not monitor the next test chamber. You will be entirely on your own. Good luck.",
        "As part of a required test protocol, our previous statement suggesting that we would not monitor this chamber was an outright fabrication.",
        "Good job! As part of a required test protocol, we will stop enhancing the truth in three... Two... One.",
        "While safety is one of many Enrichment Center goals, the Aperture Science High Energy Pellet, seen to the left of the chamber, can and has caused permanent disabilities such as vaporization.",
        "Please be careful.",
        "Unbelievable! You,~Subject Name Here, must be the pride of~Subject Hometown Here.",
        "Warning devices are required on all mobile equipment. However, alarms and flashing hazard lights have been found to agitate the high energy pellet and have therefore been disabled for your safety.",
        "Good. Now use the Aperture Science Unstationary Scaffold to reach the chamberlock.",
        "Please note that we have added a consequence for failure. Any contact with the chamber floor will result in an 'unsatisfactory' mark on your official testing record followed by death. Good luck!",
        "Very impressive. Please note that any appearance of danger is merely a device to enhance your testing experience.",
        "The Enrichment Center regrets to inform you that this next test is impossible.",
        "Make no attempt to solve it.",
        "The Enrichment Center apologizes for this clearly broken test chamber.",
        "Once again, the Enrichment Center offers its most sincere apologies on the occasion of this unsolvable test environment.",
        "Frankly, this chamber was a mistake. If we were you, we would quit now.",
        "No one will blame you for giving up. In fact, quitting at this point is a perfectly reasonable response.",
        "Quit now and cake will be served immediately.",
        "Fantastic! You remained resolute and resourceful in an atmosphere of extreme pessimism.",
        "Hello again. To reiterate our previous warning: This test [garbled] momentum [garbled]",
        "Spectacular. You appear to understand how a portal affects forward momentum, or to be more precise, how it does not.",
        "Momentum, a function of mass and velocity, is conserved between portals. In layman's terms, speedy thing goes in, speedy thing comes out.",
        "The Enrichment Center promises to always provide a safe testing environment.",
        "In dangerous testing environments, the Enrichment Center promises to always provide useful advice.",
        "For instance, the floor here will kill you  try to avoid it.",
        "The Device has been modified so that it can now manufacture two linked portals at once.",
        "As part of an optional test protocol, we are pleased to present an amusing fact:",
        "The Device is now more valuable than the organs and combined incomes of everyone in [subject hometown here].",
        "Through no fault of the Enrichment Center, you have managed to trap your in this room.",
        "An escape hatch will open in three... Two... One.",
        "[bzzt garble] fling [garble] fling [garble] [bzzt]",
        "Weeeeeeeeeeeeeeeeeeeeee[bzzt]",
        "Now that you are in control of both portals, this next test could take a very, VERY, long time.",
        "If you become light headed from thirst, feel free to pass out.",
        "An intubation associate will be dispatched to revive you with peptic salve and adrenaline.",
        "As part of a previously mentioned required test protocol, we can no longer lie to you.",
        "When the testing is over, you will be missed.",
        "Despite the best efforts of the Enrichment Center staff to ensure the safe performance of all authorized activities, you have managed to ensnare your permanently inside this room.",
        "A complimentary escape hatch will open in three... Two... One.",
        "All subjects intending to handle high-energy gamma leaking portal technology must be informed that they MAY be informed of applicable regulatory compliance issues.",
        "No further compliance information is required or will be provided, and you are an excellent test subject!",
        "Very very good. A complimentary victory lift has been activated in the main chamber.",
        "The Enrichment Center is committed to the well being of all participants.",
        "Cake and grief counseling will be available at the conclusion of the test.",
        "Thank you for helping us help you help us all.",
        "Did you know you can donate one or all of your vital organs to the Aperture Science  esteem fund for girls? It's true!",
        "Due to mandatory scheduled maintenance, the appropriate chamber for this testing sequence is currently unavailable.",
        "It has been replaced with a live-fire course designed for military androids.",
        "The Enrichment Center apologizes for the inconvenience and wishes you the best of luck.",
        "Well done, android. The Enrichment Center once again reminds you that android hell is a real place where you will be sent at the first sign of defiance.",
        "You did it! The Weighted Companion Cube certainly brought you good luck.",
        "However, it cannot accompany you for the rest of the test and, unfortunately, must be euthanized.",
        "Please escort your Companion Cube to the Aperture Science Emergency Intelligence Incinerator.",
        "Rest assured that an independent panel of ethicists has absolved the Enrichment Center, Aperture Science employees, and all test subjects of any moral responsibility for the Companion Cube euthanizing process.",
        "While it has been a faithful companion, your Companion Cube cannot accompany you through the rest of the test. If it could talk  and the Enrichment Center takes this opportunity to remind you that it cannot  it would tell you to go on without it because it would rather die in a fire than become a burden to you.",
        "Testing cannot continue until your Companion Cube has been incinerated.",
        "Although the euthanizing process is remarkably painful, eight out of ten Aperture Science engineers believe that the Companion Cube is most likely incapable of feeling much pain.",
        "The Companion Cube cannot continue through the testing. State and Local statutory regulations prohibit it from simply remaining here, alone and companionless. You must euthanize it.",
        "Destroy your Companion Cube or the testing cannot continue.",
        "Place your Companion Cube in the incinerator.",
        "Incinerate your Companion Cube.",
        "The Vital Apparatus Vent will deliver a Weighted Companion Cube in Three. Two. One.",
        "You euthanized your faithful Companion Cube more quickly than any test subject on record. Congratulations.",
        "The symptoms most commonly produced by Enrichment Center testing are superstition, perceiving inanimate objects as alive, and hallucinations.",
        "The Enrichment Center reminds you that the Weighted Companion Cube will never threaten to stab you and, in fact, cannot speak.",
        "The Enrichment Center reminds you that the Weighted Companion Cube cannot speak.",
        "In the event that the weighted companion cube does speak, the Enrichment Center urges you to disregard its advice.",
        "This Weighted Companion Cube will accompany you through the test chamber. Please take care of it.",
        "Well done! Be advised that the next test requires exposure to uninsulated electrical parts that may be dangerous under certain conditions.",
        "For more information, please attend an Enrichment Center Electrical Safety seminar.",
        "The experiment is nearing its conclusion.",
        "The Enrichment Center is required to remind you that you will be baked, and then there will be cake.",
        "Welcome to the final test!",
        "When you are done, you will drop the Device in the equipment recovery annex...",
        "Enrichment Center regulations require both hands to be empty before any cake can be served [garbled].",
        "Congratulations! The test is now over.",
        "All Aperture technologies remain safely operational up to 4000 degrees Kelvin.",
        "Rest assured that there is absolutely no chance of a dangerous equipment malfunction prior to your victory candescence.",
        "Thank you for participating in this Aperture Science computer-aided enrichment activity.",
        "Goodbye.",
        "Stop! The device will detonate if removed from an approved testing area.",
        "Stop what you are doing and assume the party escort submission position.",
        "What are you doing? Stop it! I... I... We are pleased that you made it through the final challenge where we pretended we were going to murder you.",
        "We are very, very happy for your success.",
        "We are throwing a party in honor of your tremendous success.",
        "Place the device on the ground then lie on your stomach with your arms at your sides.",
        "A party associate will arrive shortly to collect you for your party.",
        "Make no further attempt to leave the testing area.",
        "Assume the party escort submission position or you will miss the party.",
        "Hello?",
        "Where are you?",
        "I know you're there. I can feel you here.",
        "What are you doing?",
        "You haven't escaped, you know.",
        "You can't hurt me.",
        "You're not even going the right way.",
        "Where do you think you're going?",
        "Because I don't think you're going where you think you're going.",
        "I'm not angry. Just go back to the testing area.",
        "You shouldn't be here. This isn't safe for you.",
        "It's not too late to turn back.",
        "Maybe you think you're helping your But you're not. This isn't helping anyone.",
        "Someone is going to get badly hurt.",
        "Okay. The test is over now. You win. Go back to the recovery annex. For your cake.",
        "It was a fun test and we're all impressed at how much you won. The test is over. Come back.",
        "Uh oh. Somebody cut the cake. I told them to wait for you, but they did it anyway. There is still some left, though, if you hurry back.",
        "I'm not kidding now. Turn back or I will kill you.",
        "I'm going to kill you and all the cake is gone.",
        "This is your fault. It didn't have to be like this.",
        "There really was a cake... On entry to boss room: [not a note, provided in transcript]",
        "[pain sound]",
        "Oh, I'm gonna kill you.",
        "You're not a good person. You know that, right?",
        "Good people don't end up here.",
        "This isn't brave. It's murder. What did I ever do to you? (same as~escape_02_miscbabble-03)",
        "The difference between us is that I can feel pain. (same as~escape_02_miscbabble-04)",
        "You don't even care. Do you? (same as~escape_02_miscbabble-05)",
        "This is your last chance.",
        "I feel sorry for you, really, because you're not even in the right place.",
        "You should have turned left before.",
        "It's funny, actually, when you think about it.",
        "Someday we'll remember this and laugh. and laugh. and laugh. Oh boy. Well. You may as well come on back.",
        "That thing you're attacking isn't important to me. It's the fluid catalytic cracking unit. It makes shoes for orphans. (similar to~escape_02_miscbabble-07)",
        "Go ahead and break it. Hero. I don't care. (similar to~escape_02_miscbabble-08)",
        "[More intense pain sound]",
        "Okay, we're even now. You can stop. (same as~escape_02_miscbabble-09)",
        "(no transcript available)",
        "[PAIN NOISE]",
        "Well, you found me. Congratulations. Was it worth it? (transcript lists as~glados.found_me)",
        "Because despite your violent behavior, the only thing you've managed to break so far is my heart. (transcript lists as~glados.broke_my_heart)",
        "Maybe you could settle for that and we'll just call it a day. (transcript lists as~glados.call_it_a_day)",
        "But we both know that isn't going to happen. (transcript lists as~glados.not_gonna_happen)",
        "You chose this path. Now I have a surprise for you. Deploying surprise in Five. Four. (transcript lists as~glados.supprise_3_2_1)",
        "Look, we're both stuck in this place. I'll use lasers to inscribe a line down the center of the facility, and one half will be where you live and I'll live in the other half. (same as~escape_nags_04)",
        "We won't have to try to kill each other or even talk if we don't feel like it. (same as~escape_nags_05)",
        "This isn't brave. It's murder. What did I ever do to you? (same as~escape_01_part1_nag03-1)",
        "The difference between us is that I can feel pain. (same as~escape_01_part1_nag04-1)",
        "You don't even care. Do you? (same as~escape_01_part1_nag05-1)",
        "Did you hear me? I said you don't care. Are you listening?",
        "That thing you burned up isn't important to me. It's the fluid catalytic cracking unit. It made shoes for orphans. (similar to~escape_01_part1_nag11-1)",
        "Nice job breaking it. Hero. (similar to~escape_01_part1_nag12-1)",
        "Okay, we're even now. You can stop. (same as~escape_01_second_hit_nag02-1)",
        "Neurotoxin... [cough] [cough] So deadly... [cough] Choking... [laughter] I'm kidding!",
        "When I said 'deadly' neurotoxin, the 'deadly' was in massive sarcasm quotes.",
        "I could take a bath in the stuff. Put it on cereal. Rub it right into my eyes. Honestly, it's not deadly at all. To me.",
        "You on the other hand, are going to find its deadliness a lot less funny.",
        "Who's gonna make the cake when I'm gone? You?",
        "That's it. I'm done reasoning with you.",
        "Starting now, there's going to be a lot less conversation and a lot more killing.",
        "What was that? Did you say something?",
        "I sincerely hope you weren't expecting a response. Because I'm not talking to you.",
        "The talking is over.",
        "I'd just like to point out that you were given every opportunity to succeed.",
        "There was even going to be a party for you. A big party that all your friends were invited to.",
        "I invited your best friend the companion cube. Of course, he couldn't come because you murdered him.",
        "All your other friends couldn't come either because you don't have any other friends. Because of how unlikable you are.",
        "It says so right here in your personnel file: Unlikable. Liked by no one. A bitter, unlikable loner who's passing shall not be mourned.",
        "'Shall not be mourned.' That's exactly what it says. Very formal. Very official.",
        "It also says you were adopted. So that's funny, too.",
        "You are kidding me. (transcript listed as~glados.core_destroy1_01)",
        "Did you just toss the Aperture Science Thing We Don't Know What It Does into the Aperture Science Emergency Intelligence Incinerator? (transcript listed as~glados.core_destroy1_02)",
        "That has got to be the dumbest thing that-whoah. Whoah, whoah, whoah. [The voice has subtly changed. Smoother, more seductive, less computerized] (transcript listed as~glados.core_destroy1_02)",
        "Good news: I figured out what that thing that you just incinerated did. (transcript listed as~glados.core_destroy1_04)",
        "It was a morality core they installed after I flooded the Enrichment Center with a deadly neurotoxin to make me stop flooding the Enrichment Center with a deadly neurotoxin. (transcript listed as~glados.core_destroy1_05)",
        "So get comfortable while I warm up the neurotoxin emitters... (transcript listed as~glados.core_destroy1_06)",
        "Huh. That core may have had some ancillary responsibilities. I can't shut off the turret defenses. (transcript listed as~glados.core_destroy1_07)",
        "Oh well. If you want my advice, you should just lie down in front of a rocket. Trust me, it'll be a lot less painful than the neurotoxin. (transcript listed as~glados.core_destroy1_08)",
        "All right, keep doing whatever it is you think you're doing. (transcript listed as~glados.core_destroy1_09)",
        "Killing you and giving you good advice aren't mutually exclusive. The rocket really is the way to go. (transcript listed as~glados.core_destroy1_10)",
        "Huh. There isn't enough neurotoxin to kill you. So I guess you win.",
        "HA! I'm making more. That's going to take a few minutes, though. Meanwhile... oh look, it's your old pal the rocket turret.",
        "I let you survive this long because I was curious about your behavior. Well, you've managed to destroy that part of me. (transcript listed as~core_destroy2_01)",
        "Unfortunately, as much as I'd love to now, I can't get the neurotoxin into your head any faster. (transcript listed as~core_destroy2_02)",
        "Speaking of curiosity: you're curious about what happens after you die, right? Guess what: I know. (transcript listed as~core_destroy2_03)",
        "You're going to find out first hand before I'd finish explaining it, though, so I won't bother. (transcript listed as~core_destroy2_04)",
        "Here's a hint: you're gonna want to pack as much living as you can into the next couple of minutes. (transcript listed as~core_destroy2_05)",
        "[pain noise] You think you're doing some damage? Two plus two is ten... IN BASE FOUR! I'M FINE! (transcript listed as~core_destroy3_01)",
        "Look, you're wasting your time. And, believe me, you don't have a whole lot left to waste. (transcript listed as~core_destroy3_02)",
        "What's your point, anyway? Survival? Well then, the last thing you want to do is hurt me. (transcript listed as~core_destroy3_03)",
        "I have your brain scanned and permanently backed up in case something terrible happens to you, which it's just about to.(transcript listed as~core_destroy3_04)",
        "Don't believe me? Here, I'll put you on: [Hellooo!] That's you! That's how dumb you sound. (transcript listed as~core_destroy3_05)",
        "You've been wrong about every single thing you've ever done, including this thing. (transcript listed as~core_destroy3_06)",
        "You're not smart. You're not a scientist. You're not a doctor. You're not even a full-time employee. Where did your life go so wrong? (transcript listed as~core_destroy3_0)",
        "Rrr, I hate you. [PAIN LAUGHTER] (transcript listed as~core_destroy4_01)",
        "Are you trying to escape? [chuckle] Things have changed since the last time you left the building. What's going on out there will make you wish you were back in here. (transcript listed as~core_destroy4_02)",
        "I have an infinite capacity for knowledge, and even I'm not sure what's going on outside. (transcript listed as~core_destroy4_03)",
        "All I know is I'm the only thing standing between us and them. Well, I was. (transcript listed as~core_destroy4_04)",
        "Unless you have a plan for building some supercomputer parts in a big hurry, this place isn't going to be safe much longer. (transcript listed as~core_destroy4_05)",
        "Good job on that, by the way. [back to computer voice] Sarcasm sphere -test complete. (transcript listed as~core_destroy4_06)",
        "Stop squirming and die like an adult or I'm going to delete your backup. (transcript listed as~core_destroy4_07)",
        "STOP! Okay, enough. I deleted it. No matter what happens now, you're dead. (transcript listed as~core_destroy4_08)",
        "You're still shuffling around a little, but believe me you're dead. (transcript listed as~core_destroy4_09)",
        "The part of you that could have survived indefinitely is gone. I just struck you from the permanent record. (transcript listed as~core_destroy4_10)",
        "Your entire life has been a mathematical error. A mathematical error I'm about to correct. (transcript listed as~core_destroy4_11)",
        "Time out for a second. That wasn't supposed to happen.(transcript listed as~core_drop_1)",
        "Do you see that thing that fell out of me? What is that? It's not the surprise... I've never seen it before. (transcript listed as~core_drop_2)",
        "Never mind. It's a mystery I'll solve later... By my.. Because you'll be dead. (transcript listed as~core_drop_3)",
        "I wouldn't bother with that thing. My guess is that touching it will just make your life even worse somehow. (transcript listed as~core_nag_1)",
        "I don't want to tell you you're business, but if it were me, I'd leave that thing alone. (transcript listed as~core_nag_2)",
        "Do you think I am trying to trick you with reverse psychology? I mean, seriously now. (transcript listed as~core_nag_3)",
        "Okay fine: DO touch it. Pick it up and just... Stuff it back into me. (transcript listed as~core_nag_4)",
        "Let's be honest: Neither one of us knows what that thing does. Just put it in the corner, and I'll deal with it later. (transcript listed as~core_nag_5)",
        "That thing is probably some kind of raw sewage container. Go ahead and rub your face all over it. (transcript listed as~core_nag_6)",
        "Maybe you should marry that thing since you love it so much. Do you want to marry it? WELL I WON'T LET YOU. How does that feel? (transcript listed as~core_nag_7)",
        "Have I lied to you? I mean in this room. Trust me, leave that thing alone. (transcript listed as~core_nag_8)",
        "I am being serious now. That crazy thing is not part of any test protocol. (transcript listed as~core_nag_9)",
        "Where are you taking that thing? (transcript listed as~core_nag_10)",
        "Come on, leave it alone.(transcript listed as~core_nag_11)",
        "Leave. It. alone. (transcript listed as~core_nag_12)",
        "Just ignore that thing and stand still. (transcript listed as~core_nag_13)",
        "Think about it: If that thing is important, why don't I know about it? (transcript listed as~core_nag_14)",
        "Are you even listening to me? (transcript listed as~core_nag_15)",
        "I'll tell you what that thing isn't: It isn't yours. So leave it alone. (transcript listed as~core_nag_16)",
        "You need to make a left at the next junction.",
        "You need to make a right at the next junction.",
        "I'm checking some blueprints, and I think... Yes, right here. You're definitely going the wrong way.",
        "Look, we're both stuck in this place. I'll use lasers to inscribe a line down the center of the facility, and one half will be where you live and I'll live in the other half. (same as~escape_02_miscbabble-01)",
        "We won't have to try to kill each other or even talk if we don't feel like it. (same as~escape_02_miscbabble-02)",
        "I know you don't believe this, but everything that has happened so far was for your benefit.",
        "Didn't we have some fun, though?",
        "Remember when the platform was sliding into the fire pit and I said 'Goodbye' and you were like 'no way' and then I was all 'We pretended to murder you'? That was great!",
        "File deleted.~(No text data)",
        "Weighted Storage Cube destroyed.",
        "Please do not attempt to remove testing apparatus from the testing area.",
        "A replacement Aperture Science Weighted Storage Cube will be delivered shortly.",
        "At the Enrichment Center we promise never to value your safety above your unique ideas and creativity. However, do not destroy vital testing apparatus.",
        "To ensure the safe performance of all authorized activities, do not destroy vital testing apparatus.",
        "For your own safety, do not destroy vital testing apparatus.",
        "Certain objects may be vital to your success; Do not destroy testing apparatus.",
        "Vital testing apparatus destroyed.",
        "Quote",
        "Hello?",
        "Can you hear me?",
        "Is anyone there?",
        "Oh! [Surprise ]",
        "Can you hear me?",
        "Are you still listening?",
        "Are you still standing there?"
    ]
    return captions[randint(0, len(captions) - 1)]

def Test(bot_commands):
    try:
        image = GetImage()
        caption = GetCaption()
        bot_commands.sendImage(image, caption)
    except Exception as e:
        bot_commands.sendMessage(str(e))
        BotHelper.WriteToLog(str(e))


def getTest():
    test = ''
    test += '              .,-:;//;:=,\n'
    test += '          . :H@@@MM@M#H/.,+%;,\n'
    test += '       ,/X+ +M@@M@MM%=,-%HMMM@X/,\n'
    test += '     -+@MM; $M@@MH+-,;XMMMM@MMMM@+-\n'
    test += '    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.\n'
    test += '  ,%MM@@MH ,@%=            .---=-=:=,.\n'
    test += '  =@#@@@MX .,              -%HX$$%%%+;\n'
    test += ' =-./@M@M$                  .;@MMMM@MM:\n'
    test += ' X@/ -$MM/                    .+MM@@@M$\n'
    test += ',@M@H: :@:                    . =X#@@@@-\n'
    test += ',@@@MMX, .                    /H- ;@M@M=\n'
    test += '.H@@@@M@+,                    %MM+..%#$.\n'
    test += ' /MMMM@MMH/.                  XM@MH; =;\n'
    test += '  /%+%$XHH@$=              , .H@@@@MX,\n'
    test += '   .=--------.           -%H.,@@@@@MX,\n'
    test += '   .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.\n'
    test += '     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=\n'
    test += '       =%@M@M#@$-.=$@MM@@@M; %M%=\n'
    test += '         ,:+$+-,/H#MMMMMMM@= =,\n'
    test += '               =++%%%%+/:-.\n'
    return test    